// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ExpandAll
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidExpandAllPackageString = "93e87f62-573e-4591-bd46-96057ed22560";
        public static Guid guidExpandAllPackage = new Guid(guidExpandAllPackageString);

        public const string guidExpandAllPackageCmdSetString = "f85837e9-9618-4b08-b7ed-289d6f4d1a2a";
        public static Guid guidExpandAllPackageCmdSet = new Guid(guidExpandAllPackageCmdSetString);

        public const string guidImagesString = "2bfb608d-37e6-4994-b27a-054f042e8898";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int ExpandAllId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}